name: classfindr
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.0
  sizer: ^2.0.15
  image: ^3.2.2
  remove_background: ^0.0.1
  form_field_validator: ^1.0.1
  carousel_slider: ^4.2.1
  animated_splash_screen: ^1.3.0
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.9.0
  csc_picker: ^0.2.7
  fluttertoast: ^8.0.8
  pinput: ^3.0.1
  firebase_core_platform_interface: ^4.8.0
  provider: ^6.0.5
  file_picker: ^4.0.10



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/2.png
    - assets/first.jpg
    - assets/img_6.png
    - assets/OIP.jpg
    - assets/abc.png
    - assets/main_bottom.png
    - assets/main_top.png
    - assets/welcome.png
    - assets/student2.jpg
    - assets/teacher2.jpg
    - assets/splash.jpg
    - assets/otp.png
    - assets/forgotpwd.png
    - assets/login.webp
